#develop
# zuul配置
zuul:
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
    semaphore:
        max-semaphores: 500
    routes:
        api-a:
          path: /services
          # 提供服务的名称，对外接口，需提供token
          serviceId: arthur-manage-serviceWeb
